# Generated by Django 3.1.4 on 2023-10-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('emaila', models.CharField(max_length=100)),
                ('telefonoa', models.IntegerField()),
                ('helbidea', models.TextField()),
                ('txartela', models.IntegerField()),
                ('harpidetza', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deskontua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('kantitatea', models.IntegerField()),
                ('isEhunekoa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('deskribapena', models.TextField()),
                ('prezioa', models.FloatField()),
                ('deskontua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.deskontua')),
                ('kategoria', models.ManyToManyField(to='web.Kategoria')),
            ],
        ),
    ]
