# Generated by Django 3.1.4 on 2023-10-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erosketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bezeroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bezeroa')),
                ('produktuak', models.ManyToManyField(to='web.Produktua')),
            ],
        ),
    ]
