# Generated by Django 3.1.4 on 2023-10-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_erosketa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktua',
            name='img',
            field=models.ImageField(default=0, upload_to='irudiak/produktuak/'),
            preserve_default=False,
        ),
    ]
