# Generated by Django 3.1.4 on 2023-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_produktua_irudia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktua',
            name='irudia',
            field=models.ImageField(upload_to='web/static/irudiak/produktuak/'),
        ),
    ]
