# Generated by Django 3.1.4 on 2023-11-02 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20231031_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produktua',
            old_name='irudia',
            new_name='img',
        ),
        migrations.AddField(
            model_name='bezeroa',
            name='herria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bezeroa',
            name='posta_kodea',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bezeroa',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='helbidea',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='txartela',
            field=models.IntegerField(null=True),
        ),
    ]
