# Generated by Django 4.2.5 on 2023-11-02 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20231031_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroa',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='helbidea',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='txartela',
            field=models.IntegerField(null=True),
        ),
    ]
