# Generated by Django 4.2.5 on 2023-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_bezeroa_user_alter_bezeroa_helbidea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroa',
            name='herria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bezeroa',
            name='posta_kodea',
            field=models.IntegerField(null=True),
        ),
    ]
