# Generated by Django 3.1.4 on 2023-11-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20231102_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='erosketa',
            name='guztira',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Karrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitateak', models.IntegerField()),
                ('bezeroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bezeroa')),
                ('produktuak', models.ManyToManyField(to='web.Produktua')),
            ],
        ),
    ]
