# Generated by Django 4.2.5 on 2023-11-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_bezeroa_herria_bezeroa_posta_kodea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bezeroa',
            old_name='user',
            new_name='user_id',
        ),
    ]
