# Generated by Django 3.1.4 on 2023-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20231106_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karrito',
            name='unitateak',
            field=models.IntegerField(default=0),
        ),
    ]
