# Generated by Django 3.1.4 on 2023-11-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20231106_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karrito',
            name='unitateak',
        ),
    ]
