# Generated by Django 4.2.5 on 2023-11-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_user_bezeroa_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bezeroa',
            old_name='user_id',
            new_name='user',
        ),
    ]
