# Generated by Django 3.1.4 on 2023-11-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20231106_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karrito',
            name='karrito_itemak',
        ),
        migrations.AddField(
            model_name='karritoitem',
            name='karrito',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.karrito'),
            preserve_default=False,
        ),
    ]
