# Generated by Django 3.1.4 on 2023-11-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_bezeroa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='erosketa',
            name='totala',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Saskia_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantitatea', models.IntegerField()),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.produktua')),
            ],
        ),
        migrations.CreateModel(
            name='Saskia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bezeroa')),
                ('saskia_items', models.ManyToManyField(to='web.Saskia_item')),
            ],
        ),
    ]
