# Generated by Django 3.1.4 on 2023-11-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20231107_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saskia',
            name='saskia_items',
        ),
        migrations.AddField(
            model_name='saskia_item',
            name='saskia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saskia_items', to='web.saskia'),
            preserve_default=False,
        ),
    ]
