# Generated by Django 3.1.4 on 2023-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20231107_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karritoitem',
            name='karrito',
        ),
        migrations.AddField(
            model_name='karrito',
            name='karrito_itemak',
            field=models.ManyToManyField(to='web.KarritoItem'),
        ),
    ]
