# Generated by Django 3.1.4 on 2023-11-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20231107_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saskia_item',
            new_name='SaskiaItem',
        ),
    ]
