# Generated by Django 3.1.4 on 2023-11-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20231107_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='saskiaitem',
            name='prezioa_og',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
