# Generated by Django 3.1.4 on 2023-11-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_saskiaitem_prezioa_og'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saskiaitem',
            old_name='prezioa_og',
            new_name='prezioa_deskontua',
        ),
    ]
